export const padSamples = {
  'C': "https://dl.dropboxusercontent.com/s/l7hw16rn8a53vy1/c.m4a",
  'Cm': "https://dl.dropboxusercontent.com/s/nkmwp0v0x9xqeqo/dsus.m4a",
  'C#': "https://dl.dropboxusercontent.com/s/8dh5xlf6y9q82es/csus.m4a",
  'C#m': "https://dl.dropboxusercontent.com/s/slzc8xfsqq9uyov/e.m4a",
  'D': "https://dl.dropboxusercontent.com/s/t4cshdx0ofpj50b/d.m4a",
  'Dm': 'https://dl.dropboxusercontent.com/s/12v05cvm23dvwu9/f.m4a',
  'D#': "https://dl.dropboxusercontent.com/s/nkmwp0v0x9xqeqo/dsus.m4a",
  'D#m': "https://dl.dropboxusercontent.com/s/br55k1ekbyx2sbo/fsus.m4a",
  'E': "https://dl.dropboxusercontent.com/s/slzc8xfsqq9uyov/e.m4a",
  'Em': "https://dl.dropboxusercontent.com/s/fqxm3xsvu3281cj/g.m4a",
  'F': "https://dl.dropboxusercontent.com/s/12v05cvm23dvwu9/f.m4a",
  'Fm': "https://dl.dropboxusercontent.com/s/suhsxnf96ek4e00/gsus.m4a",
  'F#': "https://dl.dropboxusercontent.com/s/br55k1ekbyx2sbo/fsus.m4a",
  'F#m': "https://dl.dropboxusercontent.com/s/uicc62ooows8v0o/a.m4a",
  'G': "https://dl.dropboxusercontent.com/s/fqxm3xsvu3281cj/g.m4a",
  'Gm': "https://dl.dropboxusercontent.com/s/ea4mq99i6jfwbiw/asus.m4a",
  'G#': "https://dl.dropboxusercontent.com/s/suhsxnf96ek4e00/gsus.m4a",
  'G#m': "https://dl.dropboxusercontent.com/s/67hworai3uj6cnf/b.m4a",
  'A': "https://dl.dropboxusercontent.com/s/uicc62ooows8v0o/a.m4a",
  'Am': "https://dl.dropboxusercontent.com/s/l7hw16rn8a53vy1/c.m4a",
  'A#': "https://dl.dropboxusercontent.com/s/ea4mq99i6jfwbiw/asus.m4a",
  'A#m': "https://dl.dropboxusercontent.com/s/8dh5xlf6y9q82es/csus.m4a",
  'B': "https://dl.dropboxusercontent.com/s/67hworai3uj6cnf/b.m4a",
  'Bm': "https://dl.dropboxusercontent.com/s/t4cshdx0ofpj50b/d.m4a"
};

export const shimmerSamples = {
  'C': "https://dl.dropboxusercontent.com/s/725gvofg5yjajy0/shimmer_c.mp3",
  'Cm': "https://dl.dropboxusercontent.com/s/2g4v382evfz46da/shimmer_dsus.mp3",
  'C#': "https://dl.dropboxusercontent.com/s/kiiefabd8fyrj60/shimmer_csus.mp3",
  'C#m': "https://dl.dropboxusercontent.com/s/npw8c20znmehk0u/shimmer_e.mp3",
  'D': "https://dl.dropboxusercontent.com/s/9uvvje40qid17e0/shimmer_d.mp3",
  'Dm': 'https://dl.dropboxusercontent.com/s/fy83gja4vfnldh7/shimmer_f.mp3',
  'D#': "https://dl.dropboxusercontent.com/s/2g4v382evfz46da/shimmer_dsus.mp3",
  'D#m': "https://dl.dropboxusercontent.com/s/ed3nibdhydyytxw/shimmer_fsus.mp3",
  'E': "https://dl.dropboxusercontent.com/s/npw8c20znmehk0u/shimmer_e.mp3",
  'Em': "https://dl.dropboxusercontent.com/s/3bsj9fcmif52ssw/shimmer_g.mp3",
  'F': "https://dl.dropboxusercontent.com/s/fy83gja4vfnldh7/shimmer_f.mp3",
  'Fm': "https://dl.dropboxusercontent.com/s/6qg4vozdis7cx71/shimmer_gsus.mp3",
  'F#': "https://dl.dropboxusercontent.com/s/ed3nibdhydyytxw/shimmer_fsus.mp3",
  'F#m': "https://dl.dropboxusercontent.com/s/zh87qloh7wyihmt/shimmer_a.mp3",
  'G': "https://dl.dropboxusercontent.com/s/3bsj9fcmif52ssw/shimmer_g.mp3",
  'Gm': "https://dl.dropboxusercontent.com/s/njo2zfejk4bno6z/shimmer_asus.mp3",
  'G#': "https://dl.dropboxusercontent.com/s/6qg4vozdis7cx71/shimmer_gsus.mp3",
  'G#m': "https://dl.dropboxusercontent.com/s/tnithfzwcyj9vea/shimmer_b.mp3",
  'A': "https://dl.dropboxusercontent.com/s/zh87qloh7wyihmt/shimmer_a.mp3",
  'Am': "https://dl.dropboxusercontent.com/s/725gvofg5yjajy0/shimmer_c.mp3",
  'A#': "https://dl.dropboxusercontent.com/s/njo2zfejk4bno6z/shimmer_asus.mp3",
  'A#m': "https://dl.dropboxusercontent.com/s/kiiefabd8fyrj60/shimmer_csus.mp3",
  'B': "https://dl.dropboxusercontent.com/s/tnithfzwcyj9vea/shimmer_b.mp3",
  'Bm': "https://dl.dropboxusercontent.com/s/9uvvje40qid17e0/shimmer_d.mp3"
};

export const guitarSamples = {
  'C': "https://dl.dropboxusercontent.com/s/snnkyvfg2q2gq9e/guitar_c.mp3",
  'Cm': "https://dl.dropboxusercontent.com/s/ndoq6r5juq68hki/guitar_dsus.mp3",
  'C#': "https://dl.dropboxusercontent.com/s/cr2mlq9l28kye5p/guitar_csus.mp3",
  'C#m': "https://dl.dropboxusercontent.com/s/y1z0dvpr293hy3r/guitar_e.mp3",
  'D': "https://dl.dropboxusercontent.com/s/5cbad7iksmye1ag/guitar_d.mp3",
  'Dm': 'https://dl.dropboxusercontent.com/s/j26wdxw67wob7o9/guitar_f.mp3',
  'D#': "https://dl.dropboxusercontent.com/s/ndoq6r5juq68hki/guitar_dsus.mp3",
  'D#m': "https://dl.dropboxusercontent.com/s/aayzjagu1ghzh5f/guitar_fsus.mp3",
  'E': "https://dl.dropboxusercontent.com/s/y1z0dvpr293hy3r/guitar_e.mp3",
  'Em': "https://dl.dropboxusercontent.com/s/6zqj2iyrcr9jzl0/guitar_g.mp3",
  'F': "https://dl.dropboxusercontent.com/s/j26wdxw67wob7o9/guitar_f.mp3",
  'Fm': "https://dl.dropboxusercontent.com/s/50tfmk6iudvwcb5/guitar_gsus.mp3",
  'F#': "https://dl.dropboxusercontent.com/s/aayzjagu1ghzh5f/guitar_fsus.mp3",
  'F#m': "https://dl.dropboxusercontent.com/s/q3sof3t14kehgl0/guitar_a.mp3",
  'G': "https://dl.dropboxusercontent.com/s/6zqj2iyrcr9jzl0/guitar_g.mp3",
  'Gm': "https://dl.dropboxusercontent.com/s/8x2x55v8bbbzm99/guitar_asus.mp3",
  'G#': "https://dl.dropboxusercontent.com/s/50tfmk6iudvwcb5/guitar_gsus.mp3",
  'G#m': "https://dl.dropboxusercontent.com/s/oi0c2nl5jof45zo/guitar_b.mp3",
  'A': "https://dl.dropboxusercontent.com/s/q3sof3t14kehgl0/guitar_a.mp3",
  'Am': "https://dl.dropboxusercontent.com/s/snnkyvfg2q2gq9e/guitar_c.mp3",
  'A#': "https://dl.dropboxusercontent.com/s/8x2x55v8bbbzm99/guitar_asus.mp3",
  'A#m': "https://dl.dropboxusercontent.com/s/cr2mlq9l28kye5p/guitar_csus.mp3",
  'B': "https://dl.dropboxusercontent.com/s/oi0c2nl5jof45zo/guitar_b.mp3",
  'Bm': "https://dl.dropboxusercontent.com/s/5cbad7iksmye1ag/guitar_d.mp3"
};
